config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "/photos", to: "home#index", as: "photos"
  get "/photos/new", to: "home#new", as: "new_photo"
  get "/photos/:id", to: "home#show", as: "photo"
  post "/photos", to: "home#create"
  
  
  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @today = Date.today
    @time = Time.zone.now
    @photos = Photo.all
    
  end
  def show
    @photo = Photo.find(params[:id])    
  end
  def new
    @photo=Photo.new
  end
  
  def create
    @photo=Photo.create(photo_params)
    redirect_to photos_path
  end
  
  def photo_params
    params.require(:photo).permit(:name, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p><%=@time%></p>
<p><%=@today%></p>

<% @photos.each do |photo| %>
<div class="photo">
  <a href="<%= photo_path(photo)%>"><%= photo.name%></a>
</div>
  <a href="<%= new_photo_path%>">new</a>

<% end %>

app/views/home/new.html.erb
<h1>Add new photo</h1>
<br></br>
<%= form_for(@photo) do |f| %>
  <p>Nazwa: <%= f.text_field(:name) %></p>
  <p>Url:   <%= f.text_field(:url) %></p>
  <%= f.submit("Zapisz") %>
<% end %>

app/views/home/show.html.erb
<h1>awesome page</h1>
<div class="photo">
  <img src="<%=@photo.url%>">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R0b0caaat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>